# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=3000"]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          # pin prettier rev to <3.0 until it is stable (non-alpha)
          - prettier@2.8.1

ci:
  autoupdate_schedule: "quarterly"
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
